#ifndef __SETTINGS_H__
#define __SETTINGS_H__

#include "bootstrap.h"

const int
	FIGURE_NUMBER = 12,
	FIGURE_SIZE = 5,
	FIGURE_VARIANTS_NUMBER = 63,
	FILLED_PIXELS_NUMBER = FIGURE_NUMBER * FIGURE_SIZE,
	MAX_FIELD_WIDTH = FILLED_PIXELS_NUMBER,
	MAX_FIELD_HEIGHT = FILLED_PIXELS_NUMBER,
	FIGURE_PLACEMENT_MAX_NUMBER = FIGURE_VARIANTS_NUMBER * FILLED_PIXELS_NUMBER;

#endif